name: 
channels:
  - conda-forge
  - openastronomy
  - astropy
  - auto
dependencies:
  - python
  - matplotlib
  - basemap
  - scipy
  - pandas
  - astropy
  - skyfield
  - aplpy
  - pyregion
  - pyephem
  - jplephem
  - sgp4
  - astroquery
  - poliastro
  - pysolar
  - sunpy
  - pip:
    - jupyter_contrib_nbextensions
    - RISE
    - jupyter-wysiwyg
    - ipywidgets
    - pyavm
    - montage-wrapper
    - pdsimage
    - pyhorizon
    - orbitalpy

    
    
